### ISSUE TITLE
Because I Can't Seem to Update or Reinstall Penumbra...

### ISSUE THREAD

**Issue by Rellawing** [Sevii77/aetherment#1]
I can't seem to do anything with aetherment either so that I can try your Frost UI. Its quite the confused process. I read the other thread with steps.

**Comment by Shiichibukai** [comment]
If you cant install penumbra then you are best directed towards their discord for support - you cant really use frost ui without it anyway. You need it to even work aetherment.

**Comment by Rellawing** [comment]
Thanks! I was able to install Frost UI, and I'm loving it!
