### ISSUE TITLE
i didnt found job-icon-macro setting in "Material UI - reborn"， and the one in "Frost UI" seem to be not-working 

### ISSUE THREAD

**Issue by indyix** [Sevii77/aetherment#3]
![image](https://github.com/user-attachments/assets/e6792234-8c35-4fb2-951d-fdabdb2217ac)
![image](https://github.com/user-attachments/assets/e97ec3e2-14ea-4866-9780-b3430892e8f1)

**Comment by indyix** [comment]
v0.1.14.0

**Comment by Sevii77** [comment]
This repository is solely for the Aetherment plugin and not any of the mods, please refer to https://github.com/ValeriaeWasTaken/Material-UI-Reborn for Material UI - Reborn and https://github.com/Sevii77/frost_ui for Frost UI. But the first screenshot is MUI:R and not Frost, don't enable both at once or fix your priorities.
