### ISSUE TITLE
Aetherment causing other plugin issues

### ISSUE THREAD

**Issue by Fbombs2000** [Sevii77/aetherment#5]
Not sure what the actual issue is.  Ex: Autoretainer and Artisan.  Disabling Aetherment allows those to run.

**Comment by Sevii77** [comment]
Some plugins seem to check the text color for some reason, v0.60.0 of Frost UI added text color support. Setting the foreground color to `#EEE1C5` seems to fix it for other people, although the devs of these plugins should ideally find a better solution than to check the text color.

**Comment by zbee** [comment]
Just as an update, since this was still happening with Artisan:
This has been fixed for Artisan in PunishXIV/Artisan#201, so in the next release, and I believe it has been fixed in AutoRetainer for quite a while.
